### ISSUE TITLE
No node found for selector: #password

### ISSUE THREAD

**Issue by jupmorenor** [lawrensylvan/linkedin-learning-courses-downloader#9]
I'm having this message when launching the program.

Unexpected error while logging in : Error: No node found for selector: #password
Unexpected error : Error: No node found for selector: #password

It seems that because of slow internet the browser doesn't have loaded completely the password part of the login when it tries to select the password field.

It is failing at line 59 of _downloader.js_
`await page.type('#password', password)`

Where should I add more time to the page to load so the program can find the password field?

**Comment by lawrensylvan** [comment]
Hi,
You could add `await timeout(5000)` to have an extra 5 second delay for instance.
Please tell me if it was helpful ! And don't hesitate to give a star if you like this repo.

**Comment by jupmorenor** [comment]
It didn't work, i tried putting the delay in different lines but the result is the same :(
